### ISSUE TITLE
Showing multile notifications in one time interval 

### ISSUE THREAD

**Issue by Olit2000** [scheich/Throughput#12]
I set the update interval to 1 second. But from time to time there seem to be two notification services running so the real throughput flashes up and is then immediately replaced by zero

**Comment by scheich** [comment]
Yes, I already noticed. Thats a big bug and needs code review/rewrite.

The workarround is to stop/start the service, then it should only update once a second.

Currently I have no time anymore to fix any bigger things - have small childrens.

If you use Lineageos, theres now a similar function in the settings to monitor the traffic.

If you can, send me your bugfix. :)

sry

**Comment by Olit2000** [comment]
I think, I found the bug (or at least a part of it). 
It could be that when you turn off the screen and then immedeatly turn it on again then the runnable will be scheduled twice: Once inside the runnable to schedule itself again and once by the broadcastListener that triggers the runnablel too -> we get two running instances where we want only one.
PS: your code is not easy to read. Please concider moving some parts to its own methods (e.g. notification constructing for wifi, mobile and airplane should each get their own method)

**Comment by scheich** [comment]
Put in boolean to check if its already running, think that fixed it. If not, please reopen issue.

@Olit2000 
Thanks for reviewing the code. Actually you are the first who ever did this. And yes its very hard to read/bad coded.
