### ISSUE TITLE
FR: Share button

### ISSUE THREAD

**Issue by Natureshadow** [scheich/Throughput#2]
I'd like to have a share button in the notification to share a text describing the current network status with some other app (e.g. to whine about the poor connection on Twitter ;)).

**Comment by scheich** [comment]
Nice idea, could be an alternative in tap action

**Comment by Natureshadow** [comment]
I was thinking about these button thingies you can place below the notification. Not sure how Android calls them.

**Comment by scheich** [comment]
Yes, thats possible, but would need more code changes.

**Comment by Tony-il-Capo** [comment]
Ridiculous feature, really... should come at least with an ON/OFF option for this in settings.

**Comment by Natureshadow** [comment]
>Ridiculous feature, really...

Yeah, somewhat :P...

**Comment by scheich** [comment]
Added it, quick an dirty.

It just puts the subtitle of the notification followed by the last known location as text.

This whole app needs a rewrite...
