### ISSUE TITLE
Share network status does not work

### ISSUE THREAD

**Issue by Natureshadow** [scheich/Throughput#5]
It only shared "Could not get current location" and no network status.

**Comment by scheich** [comment]
Do you have given the location permission, do you have the location in other apps?

**Comment by Natureshadow** [comment]
1. Yes, 2. yes.

But: I do not have NLP enabled, so it waits until it gets GPS.

I don't understand why the location is even needed for anything.

**Comment by scheich** [comment]
For me it makes only sense to share the current network status with the current location.

**Comment by scheich** [comment]
You can disable the in tap function and share the notification as screenshot, then you dont have the location.

**Comment by scheich** [comment]
Currently only works, if last known location is provided, needs network location provider.

**Comment by Natureshadow** [comment]
Please treat this as a bug. The only way to use Throughput at this time is uninstalling it.

**Comment by Natureshadow** [comment]
Again: Why on earth does it want a location in the first place?

**Comment by scheich** [comment]
You can use the older version.
