### ISSUE TITLE
Keeps searching for location all day

### ISSUE THREAD

**Issue by Natureshadow** [scheich/Throughput#6]
Throughput keeps trying to acquire a location all day, draining battery.

Why do I even need the location?

**Comment by scheich** [comment]
Its for the share feature, you requested. If its enabled, it tries to get the location. It can be implemented in a better way, at the  moment its only another pending intent for the notification. Another solution with less background activity would be an own activity for this job.

Can you write it?

**Comment by scheich** [comment]
Should only search if on tap action is set to share, currently this is by design, please provide better solution.
